set(srcs            "common/misc/dsps_pwroftwo.cpp"
                    "common/misc/aes3_tie_log.c"
                    "dotprod/float/dsps_dotprod_f32_ae32.S"
                    "dotprod/float/dsps_dotprod_f32_m_ae32.S"
                    "dotprod/float/dsps_dotprode_f32_ae32.S"
                    "dotprod/float/dsps_dotprode_f32_m_ae32.S"
                    "dotprod/float/dsps_dotprod_f32_ansi.c"
                    "dotprod/float/dsps_dotprode_f32_ansi.c"
                    "dotprod/float/dsps_dotprod_f32_aes3.S"
                    "dotprod/float/dsps_dotprod_f32_arp4.S"
                    "dotprod/float/dsps_dotprode_f32_arp4.S"

                    "dotprod/fixed/dsps_dotprod_s16_ae32.S"
                    "dotprod/fixed/dsps_dotprod_s16_m_ae32.S"
                    "dotprod/fixed/dsps_dotprod_s16_ansi.c"
                    "dotprod/fixed/dsps_dotprod_s16_arp4.S"

                    "dotprod/float/dspi_dotprod_f32_ansi.c"
                    "dotprod/float/dspi_dotprod_off_f32_ansi.c"
                    "dotprod/fixed/dspi_dotprod_s16_ansi.c"
                    "dotprod/fixed/dspi_dotprod_u16_ansi.c"
                    "dotprod/fixed/dspi_dotprod_s8_ansi.c"
                    "dotprod/fixed/dspi_dotprod_u8_ansi.c"
                    "dotprod/fixed/dspi_dotprod_off_s16_ansi.c"
                    "dotprod/fixed/dspi_dotprod_off_u16_ansi.c"
                    "dotprod/fixed/dspi_dotprod_off_s8_ansi.c"
                    "dotprod/fixed/dspi_dotprod_off_u8_ansi.c"

                    "dotprod/fixed/dspi_dotprod_s16_aes3.S"
                    "dotprod/fixed/dspi_dotprod_u16_aes3.S"
                    "dotprod/fixed/dspi_dotprod_off_s16_aes3.S"
                    "dotprod/fixed/dspi_dotprod_off_u16_aes3.S"
                    "dotprod/fixed/dspi_dotprod_s8_aes3.S"
                    "dotprod/fixed/dspi_dotprod_u8_aes3.S"
                    "dotprod/fixed/dspi_dotprod_off_u8_aes3.S"
                    "dotprod/fixed/dspi_dotprod_off_s8_aes3.S"

                    "dotprod/fixed/dspi_dotprod_s16_arp4.S"
                    "dotprod/fixed/dspi_dotprod_s8_arp4.S"
                    "dotprod/fixed/dspi_dotprod_u16_arp4.S"
                    "dotprod/fixed/dspi_dotprod_u8_arp4.S"
                    "dotprod/fixed/dspi_dotprod_off_s16_arp4.S"
                    "dotprod/fixed/dspi_dotprod_off_u16_arp4.S"
                    "dotprod/fixed/dspi_dotprod_off_s8_arp4.S"
                    "dotprod/fixed/dspi_dotprod_off_u8_arp4.S"

                    "matrix/mul/float/dspm_mult_3x3x1_f32_ae32.S"
                    "matrix/mul/float/dspm_mult_3x3x3_f32_ae32.S"
                    "matrix/mul/float/dspm_mult_4x4x1_f32_ae32.S"
                    "matrix/mul/float/dspm_mult_4x4x4_f32_ae32.S"
                    "matrix/mul/float/dspm_mult_f32_ae32.S"
                    "matrix/mul/float/dspm_mult_f32_aes3.S"
                    "matrix/mul/float/dspm_mult_f32_ansi.c"
                    "matrix/mul/float/dspm_mult_f32_arp4.S"
                    "matrix/mul/float/dspm_mult_ex_f32_ansi.c"
                    "matrix/mul/float/dspm_mult_ex_f32_ae32.S"
                    "matrix/mul/float/dspm_mult_ex_f32_arp4.S"
                    "matrix/mul/float/dspm_mult_ex_f32_aes3.S"
                    "matrix/mul/fixed/dspm_mult_s16_ae32.S"
                    "matrix/mul/fixed/dspm_mult_s16_m_ae32_vector.S"
                    "matrix/mul/fixed/dspm_mult_s16_m_ae32.S"
                    "matrix/mul/fixed/dspm_mult_s16_ansi.c"
                    "matrix/mul/fixed/dspm_mult_s16_aes3.S"
                    "matrix/mul/fixed/dspm_mult_s16_arp4.S"
                    "matrix/add/float/dspm_add_f32_ansi.c"
                    "matrix/add/float/dspm_add_f32_ae32.S"
                    "matrix/addc/float/dspm_addc_f32_ansi.c"
                    "matrix/addc/float/dspm_addc_f32_ae32.S"
                    "matrix/mulc/float/dspm_mulc_f32_ansi.c"
                    "matrix/mulc/float/dspm_mulc_f32_ae32.S"
                    "matrix/sub/float/dspm_sub_f32_ansi.c"
                    "matrix/sub/float/dspm_sub_f32_ae32.S"
                    "matrix/mat/mat.cpp"

                    "math/mulc/float/dsps_mulc_f32_ansi.c"
                    "math/addc/float/dsps_addc_f32_ansi.c"
                    "math/mulc/fixed/dsps_mulc_s16_ansi.c"
                    "math/mulc/fixed/dsps_mulc_s16_ae32.S"
                    "math/add/float/dsps_add_f32_ansi.c"
                    "math/add/fixed/dsps_add_s16_ansi.c"
                    "math/add/fixed/dsps_add_s16_ae32.S"
                    "math/add/fixed/dsps_add_s16_aes3.S"
                    "math/add/fixed/dsps_add_s8_ansi.c"
                    "math/add/fixed/dsps_add_s8_aes3.S"

                    "math/sub/float/dsps_sub_f32_ansi.c"
                    "math/sub/fixed/dsps_sub_s16_ansi.c"
                    "math/sub/fixed/dsps_sub_s16_ae32.S"
                    "math/sub/fixed/dsps_sub_s16_aes3.S"
                    "math/sub/fixed/dsps_sub_s8_ansi.c"
                    "math/sub/fixed/dsps_sub_s8_aes3.S"

                    "math/mul/float/dsps_mul_f32_ansi.c"
                    "math/mul/fixed/dsps_mul_s16_ansi.c"
                    "math/mul/fixed/dsps_mul_s16_ae32.S"
                    "math/mul/fixed/dsps_mul_s16_aes3.S"
                    "math/mul/fixed/dsps_mul_s8_ansi.c"
                    "math/mul/fixed/dsps_mul_s8_aes3.S"

                    "math/mulc/float/dsps_mulc_f32_ae32.S"
                    "math/addc/float/dsps_addc_f32_ae32.S"
                    "math/add/float/dsps_add_f32_ae32.S"
                    "math/sub/float/dsps_sub_f32_ae32.S"
                    "math/mul/float/dsps_mul_f32_ae32.S"
                    "math/sqrt/float/dsps_sqrt_f32_ansi.c"

                    "fft/float/dsps_fft2r_fc32_ae32_.S"
                    "fft/float/dsps_fft2r_fc32_aes3_.S"
                    "fft/float/dsps_fft2r_fc32_arp4.S"
                    "fft/float/dsps_fft2r_fc32_ansi.c"
                    "fft/float/dsps_fft2r_fc32_ae32.c"
                    "fft/float/dsps_bit_rev_lookup_fc32_aes3.S"
                    "fft/float/dsps_fft4r_fc32_ansi.c"
                    "fft/float/dsps_fft4r_fc32_ae32.c"
                    "fft/float/dsps_fft4r_fc32_ae32_.S"
                    "fft/float/dsps_fft4r_fc32_aes3_.S"
                    "fft/float/dsps_fft4r_fc32_arp4.S"
                    "fft/float/dsps_fft2r_bitrev_tables_fc32.c"
                    "fft/float/dsps_fft4r_bitrev_tables_fc32.c"
                    "fft/fixed/dsps_fft2r_sc16_ae32.S"
                    "fft/fixed/dsps_fft2r_sc16_ansi.c"
                    "fft/fixed/dsps_fft2r_sc16_aes3.S"
                    "fft/fixed/dsps_fft2r_sc16_arp4.S"

                    "dct/float/dsps_dct_f32.c"
                    "dct/float/dsps_dctiv_f32.c"
                    "dct/float/dsps_dstiv_f32.c"
                    "support/snr/float/dsps_snr_f32.cpp"
                    "support/sfdr/float/dsps_sfdr_f32.cpp"
                    "support/misc/dsps_d_gen.c"
                    "support/misc/dsps_h_gen.c"     
                    "support/misc/dsps_tone_gen.c"
                    "support/cplx_gen/dsps_cplx_gen.c"
                    "support/cplx_gen/dsps_cplx_gen.S"
                    "support/cplx_gen/dsps_cplx_gen_init.c"
                    "support/mem/esp32s3/dsps_memset_aes3.S"
                    "support/mem/esp32s3/dsps_memcpy_aes3.S"
                    "support/view/dsps_view.cpp"
                    "windows/hann/float/dsps_wind_hann_f32.c"
                    "windows/blackman/float/dsps_wind_blackman_f32.c"
                    "windows/blackman_harris/float/dsps_wind_blackman_harris_f32.c"
                    "windows/blackman_nuttall/float/dsps_wind_blackman_nuttall_f32.c"
                    "windows/nuttall/float/dsps_wind_nuttall_f32.c"
                    "windows/flat_top/float/dsps_wind_flat_top_f32.c"
                    "conv/float/dsps_conv_f32_ansi.c"
                    "conv/float/dspi_conv_f32_ansi.c"
                    "conv/float/dsps_conv_f32_ae32.S"
                    "conv/float/dsps_corr_f32_ansi.c"
                    "conv/float/dsps_corr_f32_ae32.S"
                    "conv/float/dsps_ccorr_f32_ansi.c"
                    "conv/float/dsps_ccorr_f32_ae32.S"
                    "iir/biquad/dsps_biquad_f32_ae32.S"
                    "iir/biquad/dsps_biquad_sf32_ae32.S"
                    "iir/biquad/dsps_biquad_f32_aes3.S"
                    "iir/biquad/dsps_biquad_f32_arp4.S"
                    "iir/biquad/dsps_biquad_sf32_arp4.S"
                    "iir/biquad/dsps_biquad_f32_ansi.c"
                    "iir/biquad/dsps_biquad_sf32_ansi.c"
                    "iir/biquad/dsps_biquad_gen_f32.c"
                    "fir/float/dsps_fir_f32_ae32.S"
                    "fir/float/dsps_fir_f32_aes3.S"
                    "fir/float/dsps_fird_f32_ae32.S"
                    "fir/float/dsps_fird_f32_aes3.S"
                    "fir/float/dsps_fird_f32_arp4.S"
                    "fir/float/dsps_fir_f32_ansi.c"
                    "fir/float/dsps_fir_init_f32.c"
                    "fir/float/dsps_fird_f32_ansi.c"
                    "fir/float/dsps_fird_init_f32.c"
                    "fir/fixed/dsps_fird_init_s16.c"
                    "fir/fixed/dsps_fird_s16_ansi.c"
                    "fir/fixed/dsps_fird_s16_ae32.S"
                    "fir/fixed/dsps_fir_s16_m_ae32.S"
                    "fir/fixed/dsps_fird_s16_aes3.S"
                    "fir/fixed/dsps_fird_s16_arp4.S"
                    "fir/float/dsps_firmr_init_f32.c"
                    "fir/float/dsps_firmr_f32_ansi.c"
                    "fir/fixed/dsps_firmr_init_s16.c"
                    "fir/fixed/dsps_firmr_s16_ansi.c"
                    "fir/resampler/dsps_resampler_mr.c"
                    "fir/resampler/dsps_resampler_ph.c"
# EKF files
                    "kalman/ekf/common/ekf.cpp"
                    "kalman/ekf_imu13states/ekf_imu13states.cpp"
                    )



set(include_dirs                "dotprod/include"
                                "support/include"
                                "support/mem/include"
                                "windows/include"
                                "windows/hann/include"
                                "windows/blackman/include"
                                "windows/blackman_harris/include"
                                "windows/blackman_nuttall/include"
                                "windows/nuttall/include"
                                "windows/flat_top/include"
                                "iir/include"
                                "fir/include"
                                "math/include"
                                "math/add/include"
                                "math/sub/include"
                                "math/mul/include"
                                "math/addc/include"
                                "math/mulc/include"
                                "math/sqrt/include"
                                "matrix/mul/include"
                                "matrix/add/include"
                                "matrix/addc/include"
                                "matrix/mulc/include"
                                "matrix/sub/include"
                                "matrix/include"
                                "fft/include"
                                "dct/include"
                                "conv/include"
                                "common/include"
                                "matrix/mul/test/include"
# EKF files
                                "kalman/ekf/include"
                                "kalman/ekf_imu13states/include"
)

set(priv_include_dirs           "dotprod/float"
                                "dotprod/fixed")

idf_component_register(SRCS ${srcs}
                      INCLUDE_DIRS ${include_dirs}
                      PRIV_INCLUDE_DIRS ${priv_include_dirs})
